<footer class="site-footer">
    	<div class="container">
        	<div class="row">
            	<!-- Usages -->
            	<div class="col-md-2">
                	<div class="widget">
                    	<h3 class="widget-title">Usages</h3>
                        <ul class="no-bullet">
                        	<li><a href="#">Account</a></li>
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">FAQ</a></li>
                        </ul>
                    </div>
                </div>
                
                <!-- Help Center --->
                <div class="col-md-2">
                	<div class="widget">
                    	<h3 class="widget-title">Help Center</h3>
                        <ul class="no-bullet">
                        	<li><a href="contact_us.php">Contact us</a></li>
                        	<li><a href="#">Legal notices</a></li>
                        	<li><a href="#">Ways to watch</a></li>
                            <li><a href="#">Speed test</a></li>
                        </ul>
                    </div>
                </div>
                
                <!-- Corporate Opportunities -->
                <div class="col-md-2">
                	<div class="widget">
                    	<h3 class="widget-title">Corporate</h3>
                        <ul class="no-bullet">
                        	<li><a href="#">Investor relations</a></li>
                            <li><a href="#">Corporate information</a></li>
                            <li><a href="#">Media Centre</a></li>
                            <li><a href="#">Jobs</a></li>
                        </ul>
                    </div>
                </div>
                <!-- Social Media -->
                <div class="col-md-2">
					<div class="widget">
						<h3 class="widget-title">Social Media</h3>
						<ul class="no-bullet">
							<li><a href="#">Facebook</a></li>
							<li><a href="#">Twitter</a></li>
							<li><a href="#">Google+</a></li>
							<li><a href="#">Pinterest</a></li>
						</ul>
					</div>
				</div>
                <!-- New Letter -->
                <div class="col-md-2">
					<div class="widget">
						<h3 class="widget-title">Newsletter</h3>
						<form action="#" class="subscribe-form">
							<input type="text" placeholder="Email Address">
						</form>
					</div>
				</div>
            </div>
        	<div class="colophon">This is the assignment project of Group 7, 2018.</div>
        </div>
    </footer>