<header class="site-header">
        	<div class="container" style="padding-bottom: 15px;">
                    <!-- Branding and Logo -->
                    <a href="index.php" id="branding">
                        <img src="img/logo.jfif" alt="" class="logo">
                        <div class="logo-copy">
                            <h1 class="site-title">Team 7 Media</h1>
                            <small class="site-description">Bring Affordable entertainment to people</small>
                        </div>
                    </a>
            </div>
            
            <div class="container">               
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
  					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    					<span class="navbar-toggler-icon"></span>
  					</button>
  					<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                            <li class="nav-item active">
                                <a class="nav-link" href="index.php">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="movie.php">Movie Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="member.php">Become A Member</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="subscription.php">Subscription</a>
                            </li>
                        </ul>
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    					</form>
  					</div>
				</nav>
            </div>
    	</header>